services:
  - type: web
    name: calendar-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_cloud.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production 